---
abstract: 'The real boolean keywords'
author:
  - 'Goro Fuji (gfx) <gfuji(at)cpan.org>'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
  ExtUtils::ParseXS: 2.21
  Test::More: 0.88
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Keyword::Boolean
name: Keyword-Boolean
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  XSLoader: 0.1
  perl: 5.11.2
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/Keyword-Boolean.git
version: 0.001
